name: emdbc_env_py3_11_9
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - numpy==1.26.4
      - scipy==1.13.1
      - pandas==2.2.3
      - matplotlib==3.10.0
      - emd-signal==1.6.0
      - scikit-learn==1.6.0
      - jupyterlab==4.3.5
